version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: food-del
      POSTGRES_USER: user
      POSTGRES_DB: food-db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: food-del-api
    ports:
      - 13000:3000

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: food-del-api-test
    depends_on:
      - db
    ports:
      - 13001:3000