version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: bebra
      POSTGRES_USER: user
      POSTGRES_DB: food-db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    environment:
      - sample=value
    image: food-del-api
    ports:
      - 13000:3000
