version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: bebra
      POSTGRES_USER: user
      POSTGRES_DB: food-db
  app:
    image: food-del-api
    ports:
      - 13000:3000
