###
GET http://localhost:13000/api/v2/users/setup

###
GET http://localhost:13000/api/v2/users

###
POST http://localhost:13000/api/v2/users/register
Content-Type: application/json

{
    "name": "John",
    "email": "bebra",
    "password": "traher"
}