const setup = ```CREATE TABLE Drivers (
driver_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
phone VARCHAR(20) NOT NULL,
location VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL
);
```;
